DROP TABLE FIDE_PAGOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROYECTOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PRESUPUESTO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_GARANTIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_COMPRA_MATERIALES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ASIGNACIONES_TB CASCADE CONSTRAINTS;

DROP TABLE FIDE_EMPLEADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PUESTO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_MATERIALES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CLIENTE_TB CASCADE CONSTRAINTS;

DROP TABLE FIDE_DIRECCION_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITO_TB CASCADE CONSTRAINTS;

DROP TABLE FIDE_CANTON_TB CASCADE CONSTRAINTS;

DROP TABLE FIDE_SUBCATEGORIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TIPO_CLIENTE_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_MAQUINARIA_TB CASCADE CONSTRAINTS;

DROP TABLE FIDE_CATEGORIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ESTADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DESCUENTO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_RESPONSABLES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAIS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ENTIDAD_EMISORA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_MANTENIMIENTO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TIPO_PRODUCTOS_TB CASCADE CONSTRAINTS;
DROP SEQUENCE FIDE_ESTADO_SEQ;
DROP SEQUENCE FIDE_EMPLEADOS_SEQ;
DROP SEQUENCE FIDE_PUESTO_SEQ;
DROP SEQUENCE FIDE_MATERIALES_SEQ;
DROP SEQUENCE FIDE_CLIENTE_SEQ;
DROP SEQUENCE FIDE_TIPO_CLIENTE_SEQ;
DROP SEQUENCE FIDE_PROVEEDORES_SEQ;
DROP SEQUENCE FIDE_MAQUINARIA_SEQ;
DROP SEQUENCE FIDE_ASIGNACIONES_SEQ;
DROP SEQUENCE FIDE_COMPRA_MATERIALES_SEQ;
DROP SEQUENCE FIDE_MANTENIMIENTO_SEQ;
DROP SEQUENCE FIDE_PRESUPUESTO_SEQ;
DROP SEQUENCE FIDE_GARANTIAS_SEQ;
DROP SEQUENCE FIDE_ENTIDAD_EMISORA_SEQ;
DROP SEQUENCE FIDE_RESPONSABLES_SEQ;
DROP SEQUENCE FIDE_PROYECTOS_SEQ;
DROP SEQUENCE FIDE_PAGOS_SEQ;
DROP SEQUENCE FIDE_DIRECCION_SEQ;
DROP SEQUENCE FIDE_DISTRITO_SEQ;
DROP SEQUENCE FIDE_CANTON_SEQ;
DROP SEQUENCE FIDE_PROVINCIA_SEQ;
DROP SEQUENCE FIDE_PAIS_SEQ;
DROP SEQUENCE FIDE_DESCUENTO_SEQ;
DROP SEQUENCE FIDE_CATEGORIAS_SEQ;
DROP SEQUENCE FIDE_SUBCATEGORIAS_SEQ;
DROP SEQUENCE FIDE_TIPO_PRODUCTOS_SEQ;

